### ISSUE TITLE
Too many underlines

### ISSUE THREAD

**Issue by xgdgsc** [IwYvI/chinolor#1]
Thanks, I like most part of the theme. I see full screen of underlines in cpp code. Is it possible to provide a version without underlines.

**Comment by iwyvi** [comment]
I think the underlines are acceptable in this theme.
If you find it annoying, you can add following configs into `settings.json` to remove the underlines.

```json
"editor.tokenColorCustomizations": {
    "[Chinolor]": {
      "textMateRules": [
        {
          "scope": ["entity.name.type"],
          "settings": {
            "fontStyle": ""
          }
        },
      ]
    },
  },
```

**Comment by xgdgsc** [comment]
Thanks. It works. Maybe you feel the under score isn't an issue with dynamic typed languages, but it really sucks in strong typed languages.
