### ISSUE TITLE
升级vscode 1.57 后light主题下自动补全看不清

### ISSUE THREAD

**Issue by xgdgsc** [IwYvI/chinolor#5]
![Screenshot_20210616_160355](https://user-images.githubusercontent.com/1189869/122182726-1e742100-cebd-11eb-8ed5-9919318316aa.png)
ctrl shift p 搜索也看不清

不知改哪个值可以

**Comment by iwyvi** [comment]
@xgdgsc 已发布 v0.2.15 ，可以更新一下

这个变化是因为 vscode 1.57 更新了列表的 focus 默认颜色 https://code.visualstudio.com/updates/v1_57#_updated-quick-pick-suggest-widget-colors

**Comment by xgdgsc** [comment]
👍  谢谢
