### ISSUE TITLE
Highlighting the active indent guide

### ISSUE THREAD

**Issue by victor-gp** [IwYvI/chinolor#6]
Hi iwyvi,

In the first place, thanks for Chinolor, it's my favorite light theme. The color scheme looks great and it has very good support for syntax highlighting.

As for the issue, could you add highlighting to the active indent guide? It would look like this:

![chinolor-highlight-active-guide](https://user-images.githubusercontent.com/43856183/125964730-1f273cb2-ab47-4a54-b9bb-6c7768f9bf77.gif)

With the color of your choice, obviously. My example uses 夏云灰 from the dark theme. 

If you're interested, the style you have to set is `editorIndentGuide.activeBackground`. If you also want to change the default color for guides, that style is `editorIndentGuide.background`.

**Comment by iwyvi** [comment]
@victor-gp Thanks for your suggestion.

I tried to set `editorIndentGuide.activeBackground` and found it is a good idea to make indent guide a different color.

But I think in light theme, 夏云灰 (#617172) is a little darker, but 明灰 (#8a988e) looks more comfortable. (60c5b8c67d6b55c4881c960588a2514342a7f89e)

**Comment by victor-gp** [comment]
I agree, it does fit the theme much better.

Thanks for adding this. :D

**Comment by iwyvi** [comment]
v0.2.16 Released
